#!/bin/bash

p=./client_proxy
f_ip=127.0.0.1
secret1=
secret3=
# 检查参数个数
if [ $# -eq 0 ]; then
    echo "Usage: $0 <strategy>"
    echo "  strategy is:"
    echo "      n1: 1year"
    echo "      n3: 3year"
    echo "      f1: forward 1year"
    echo "      f3: forward 3year"
    exit 1
fi

# 根据参数执行不同的代码
case $1 in
    "f1")
        $p 9101 $f_ip 8898 $secret1 &
        ;;
    "f3")
        $p 9103 $f_ip 8899 $secret3 &
        ;;
    "n1")
        $p 9201 127.0.0.1 2052 $secret1 &
        ;;
    "n3")
        $p 9203 127.0.0.1 5555 $secret3 &
        ;;
    *)
        echo "strategy <$1> not support"
        exit 1
        ;;
esac